version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - 8080:8080

  backend:
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - new_network
    depends_on:
      - postgres

  postgres:
    build: ./db
    ports:
      - 5432:5432
    networks:
      - new_network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
networks:
  new_network: 
