version: "3.9"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 8080:8080

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app/backend
    ports:
      - 5000:5000
    depends_on: 
      - postgres

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
