version: "3.9"
services:
  postgres:
    build: ./db
    ports:
      - 5432:5432
    networks:
      - new_network

  frontend:
    build: ./frontend
    ports:
      - 8080:8080

  backend:
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - new_network
    depends_on:
      - postgres

networks:
  new_network: 
